### ISSUE TITLE
GPU Roadmap

### ISSUE THREAD

**Issue by dcmvdbekerom** [radis/radis#144]
**GPU Roadmap**

@pkj-m, @erwanp, and others!
Starting from version [0.9.26](https://github.com/radis/radis/releases/tag/0.9.26) RADIS has experimental GPU support as the result of a very succesful GSoC2020 project. In this roadmap I'll try to condense some concrete points what we'd need for a general GPU support aimed at RADIS v1.0.

My personal aim would be to have FULL GPU support for v1.0, to the extend that we could make it the default RADIS option, provided, of course, the user has a GPU.

- [ ] **Decide on- and implement a data format:**
    Device memory is expensive on a GPU, and we want to use huge databases. To get the most out of our GPU implementation, we want to use memory as efficiently as possible. Some quantities in a database, like e.g. pressure broadening temperature coefficient, have only two or three significant digits, it would be a waste to spend the full 4 bytes of an fp32 on this. We should choose an efficient scheme that does right to the significant digits of each quantity in the database.

    Related: https://github.com/radis/radis/issues/118   
    Edit @erwanp  : also to #166 

- [ ] **Eliminate fp32 atomic-adds:**
    The current experimental GPU implementation makes use of fp32 atomic-adds. These guarantee that the read-add-write operation is not interrupted by other instructions. The drawback of this is that it leads to non-deterministic behaviour, see also the discussion on the [slack channel](https://app.slack.com/client/T9E5R3R9S/C018X7XGMBP/thread/C014RGS3Z6E-1607214439.007400). A solution could involve sorting the blocks on the output spectral axis instead of the input. This may take a performance hit, so the user should be able to decide which implementation it wants.

- [ ] **Add GPU support for other species and non-eq spectra:**
    Currently only equilibrium CO2 spectra is supported. Eventually we want to be able to make non-equilibirium spectra as well. This raise some new issues, for example with how we will supply the partition functions that may have a different format for every species.
    
    Related: https://github.com/radis/radis/issues/45, https://github.com/radis/radis/issues/150

- [ ] **Add GPU support for line-of-sight:**
    The new algorithm shows great potential for line-of-sight spectra, but this is not implemented yet. We should first implement this in CPU code to see what works and what does not, but then should also implement this in GPU code.
    
    Related: https://github.com/radis/radis/issues/143

- [x] **Add more databases:**
    The real power of GPU implementation is revealed only when it works with MASSIVE databases, so we should work on an easy way to download these databases to RADIS.

    Related: https://github.com/radis/radis/issues/34

- [ ] **Close the loop; implement CPU code in the same way as GPU:**
    While the CPU implementation is very efficient, there's still big improvements to be made. Once the GPU code works, we can program a CPU code in the same way and compile it in Cython. Preliminary work shows another factor of ~10 speedup for CPU implementation should be possible this way.

---
<sub>*Tip : you can vote for [New Features](https://github.com/radis/radis/issues/79) on https://feathub.com/radis/radis*</sub>

**Comment by erwanp** [comment]
Hello @dcmvdbekerom , thanks for writing this exhaustive post !! 

@vmol on Slack may be able to help on the "Eliminate fp32 atomic-adds" ? 

I'm surprised that only CO2 is supported for GPU calculations. I was under the impression that the final implementation of @pkj-m , and in particular [these lines](https://github.com/radis/radis/blob/8fb445539125517b91209eb728fa7021383949e0/radis/lbl/factory.py#L1026), would be fetching the partition functions calculated in RADIS/tabulated in TIPS for any species. 
However, it is true that we did not test it for anything other than CO2. Could be nice to have a CH4 run for instance, and open a dedicated issue to extend GPU to all species under equilibrium if it's not currently possible.   @pkj-m maybe you tried already ? 

Extension to nonequilibrium will be another challenge, and be very molecule specific. It's related to another Enhancement I just opened (#150), which is part of the Roadmap discussions : should we focus on high-performance line-resolution, or rovibrational energy calculations ? (to me the answer is clear, also because we have limited ressources ;) )

**Comment by dcmvdbekerom** [comment]
Oops you're probably right that it is compatible with other molecules alreaady! Well that's an easy check in that case :)

**Comment by pkj-m** [comment]
Hey Apologies for the late reply. I completely missed the notifications from this thread for some reason :sweat_smile: 

@erwanp I don't think I actually tried to calculate non-CO2 spectra on the GPU, but like you mentioned, it shouldn't be a problem. Maybe we should try it once if you haven't already done it yet?

@dcmvdbekerom I would be happy to help out with extending GPU support for line-of-sight spectras, as well as updating the current CPU code to a Cython-ized implementation. I am also quite interested in the problem of reducing the memory footprint of the database on the GPU.

I also feel if we make some good progress on these issues, it might make it easy to onboard a new collaborator through GSoC for the GPU related tasks next year.

**Comment by erwanp** [comment]
One thing I'm not sure so sure is if the current GPU draft implementation has both resonant [self] and external [usually : air] pressure broadening ?
