### ISSUE TITLE
Update How-to-Cite and Readme with new paper

### ISSUE THREAD

**Issue by erwanp** [radis/radis#156]
### 🎯 Todo

Mention new paper, update "how to cite".

Change here:
- [x] update links in [bibliography](https://radis.readthedocs.io/en/latest/references/references.html#bibliography)
- [x] add the paper to the [how to cite?](https://radis.readthedocs.io/en/latest/references/references.html#cite) [we should cite both papers : "using the code [X] with the new algorithm [Y]" ] . Until we have the Community paper to replace the initial citation. 
- [x] Add a doi badge in the README https://github.com/radis/radis ? 
- [ ] (optional ?) mention the paper directly on the Landing page ? https://radis.github.io/ 

Also mention the 1st Bibliography reference consistently in the code and in the online doc. For instance : 
- [ ] here https://radis.readthedocs.io/en/latest/lbl/gpu.html#behind-the-scenes-how-does-the-gpu-calculation-actually-work
- [ ] https://radis.readthedocs.io/en/latest/lbl/lbl.html#lineshape-optimizations
- [ ] and pretty much anywhere we use to mention "DLM" 

@dcmvdbekerom if you want to have a try to modifying the online docs. It's very easy, just find the corresponding .rst file under  [radis/docs](https://github.com/radis/radis/tree/develop/docs) !

**Comment by dcmvdbekerom** [comment]
I was thinking about the "how to cite"; we should ideally make a RADIS method that outputs the used references in a Bibtex or similar format that includes references for all the used linelists. This way the people who compiled the line-lists will also get proper credit.

**Comment by erwanp** [comment]
Very good idea, and very good idea to make it a Bibtex too ! Could be embeded in the Spectrum metadata so you can share the Spectrum without loosing the references (ideally, the Spectrum will look like a pdf using a remix of your pypdfplot code).
Small attention point : make sure references are added when merging spectra in MergeSlabs / SerialSlabs.

**Comment by erwanp** [comment]
Fixed by f9d63ef
