### ISSUE TITLE
Update GPU documentation

### ISSUE THREAD

**Issue by erwanp** [radis/radis#289]
### 🎯 Todo

Online GPU docs date back from @pkj-m 's project one year ago and could be updated ; mostly with new #266 #274 improvements

- [x] update [gpu page](https://radis.readthedocs.io/en/latest/lbl/gpu.html#label-radis-gpu) 
- [x] update [lbl/gpu section](https://radis.readthedocs.io/en/latest/lbl/lbl.html#gpu-accelerated-spectrum-calculation)
- [x] maybe, [add a demo](https://github.com/radis/radis) on the README?   

For instance the GPU widget example : 

https://user-images.githubusercontent.com/16088743/121789972-f34ab280-cbda-11eb-99b0-d7ba019d80d5.mp4

(a link can be included on the docs too ; not sure if mp4 is supported/read  on Readthedocs?)

**Comment by dcmvdbekerom** [comment]
Let's do this after / at the end of https://github.com/radis/radis/pull/274 as some details may still change!
