### ISSUE TITLE
todo: add Warnings/prevent downloading very large files 🌳 

### ISSUE THREAD

**Issue by erwanp** [radis/radis#476]
### 💭 Description

With the update of ExoMol API and more RADIS user using it; I believe it's important to prevent unexpectedly large file download. 

For two reasons : 
- user experience & performance  (ex : Recommended ExoMol database for [SiO](https://exomol.com/data/molecules/SiO/28Si-16O/) was EBJT , few MB, it became SiOuvenir, 1 GB.  -->  a first download would now take ages;  and it takes a lot of space on your disk 
- environmental reasons 🌳   : downloading tens of GBs  (order of magnitude : ~ download 20 GB ~ 1 kg CO2 emitted)

---
_details:_ 

Orders of magnitude : 
~ 0.1 - 1 kWh electricity / GB transfered . Source [IEA](https://www.iea.org/data-and-statistics/charts/assumptions-for-energy-intensity-of-data-centres-data-transmission-networks-and-devices-in-2019)
~ 50 - 500  gCO2 / kWh electricity . Source [CarbonAnalyzer](https://theshiftproject.org/en/carbonalyser-browser-extension/), [ElectricityMap](https://app.electricitymap.org/)

==> 5 - 500 gCO2 / GB transfered  [large range] i.e. log-average of  **20 GB transfered = 1 kg CO2** [2 to 200 GB / kg CO2, depending on conditions] .

For reference, 2T CO2 / year (objective carbon neutrality 2050) = 5.5 kg day ==> you don't want to waste 1 kg by downloading 20 GB on a mistake. 

---

I'd suggest we add a warning when loading 

- [ ] decide on the threshold. I'd say ~ 1 GB. 
- [ ] find size of file before downloading 
- [ ] let user decide. 

Possible implementaiton : a key in radis.config

```
import radis
radis.config["PREVENT_LARGE_DOWNLOAD_ABOVE_X_GB"] =  1   # by default 
```

which can be reset by users in a session or globally.
