### ISSUE TITLE
📚 todo: Provide compiled CUDA kernel w/o requiring CUDA toolkit

### ISSUE THREAD

**Issue by dcmvdbekerom** [radis/radis#603]
### 💭 Description

Until now, the GPU part of radis has relied on cupy+cuda toolkit to run. This has resulted in issues in the past:

https://github.com/radis/radis/issues/515
https://github.com/radis/radis/issues/583

In researching the issue, it first seemed we need to compile the code, making it a c compilation issue. (See: https://github.com/radis/radis/issues/596)

I have now found that the CUDA kernel can be launched from python completely without compilation, using ctypes and nvcuda.dll, provided the CUDA kernel (.cu file) is compiled to .ptx.

- [x] Compile .cu to .ptx with NVCC
- [x] Launch kernel using CUDA driver API
- [x] Wrap driver api to python (ctypes or cffi)
- [x] Write numpy.ndarray subclass for device memory management
- [x] Figure out how to deal with constant memory
- [x] Figure out how to deal with structs
- [x] Rewrite .cu file to include cufft (stop relying on cupy)
- [x] Start on radis PR (single spectrum)
- [x] multiple spectra
- [x] Build CPU compatibility dll
- [x] Test on linux system
